### ISSUE TITLE
Problemas creados: pdf o html? 

### ISSUE THREAD

**Issue by soledadgbenot** [marcogalliani/trabajo01grupotd2023#1]
Subo los enunciados de los problemas de la parte individual en un archivo de tipo PDF partiendo de un Rmarkdown

**Comment by marcogalliani** [comment]
Sí creo que la major cosa es de usar archivos pdf porque este tipo de archivo se puede previsualizar directamente en Github (para visualizar html tenemos que descargar el archivo)
