### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by jesfalgar** [marcogalliani/trabajo01grupotd2023#2]
Revisar que están los problemas y enunciados subidos de todos los integrantes del grupo

**Comment by marcogalliani** [comment]
Estos son los requisitos que cada uno tiene cumplir
| Nombre | Enunciados  | Soluciones |
|--------|--------|--------|
| Jesus | <ul><li>- [x] </li></li></ul>  | <ul><li>- [x] </li></li></ul> |
| Soledad | <ul><li>- [x] </li></li></ul> | <ul><li>- [x] </li></li></ul> |
| Marco | <ul><li>- [x] </li></li></ul> | <ul><li>- [x] </li></li></ul> |
| Ferran | <ul><li>- [x] </li></li></ul> | <ul><li>- [x] </li></li></ul> | 

Si me falta algo comenta porfavor

**Comment by soledadgbenot** [comment]
No me deja darle al tick de confirmado, pero ya está todo
