### ISSUE TITLE
Eliminación archivos duplicados y utilización de un solo archivo para los métodos bajo incertidumbre 

### ISSUE THREAD

**Issue by marcogalliani** [marcogalliani/trabajo01grupotd2023#4]
Cada uno está trabajando con un archivo diferente conteniente las funciones con los métodos bajo incertidumbre. En mi opinion tenemos que usar un solo archivo, si está de acuerdo voy a editar

**Comment by soledadgbenot** [comment]
Perfecto, así está mucho mejor:)

**Comment by marcogalliani** [comment]
Vale, he eliminado la carpeta `include`. Ahora el unico archivo con las funciones está en "scripts/teoriadecision_funciones_incertidumbre.R". @pompolompo y @jesfalgar atención porque el vuestro código R no funciona actualmente porque no tiene la posición correcta de el archivo cuando hacéis `source()`

**Comment by pompolompo** [comment]
Listo!
